// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqrzmoipagiallkdgxuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxcnptb2lwYWdpYWxsa2RneHV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MjM3MjUsImV4cCI6MjA2NjA5OTcyNX0.o0IJwhQDSl9cU-Qq-UbwA9fo_qHDtBA8ED06HnHZnCI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);